version: "3.8"
services:
  frontend:
    image: "frontend"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "3000:80"
